repository_type: pipeline
lint:
  files_unchanged:
    - .gitattributes
  files_exist:
    - conf/igenomes.config
  nextflow_config:
    - config_defaults:
      - params.report_template
      - params.report_css
      - params.report_logo
  actions_ci: False
